import React from 'react';

const Sports = () => {
    return (
        <div>
            <h2>I am sports page</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet modi velit eius iusto minima tempora? Quidem, provident esse? Ipsa debitis autem repellendus dolores cum incidunt est odit nemo a magnam modi esse, rerum sint, quasi earum recusandae sit vel aliquam. Voluptatum, harum consequatur exercitationem temporibus id amet voluptates dicta repellat aspernatur, enim natus ipsum adipisci quod ex? Nihil nesciunt, consequuntur quibusdam sapiente omnis, quo repellendus itaque laboriosam dolorem minima officia quia aliquid soluta culpa voluptas! Quas voluptate amet, vero corrupti consequatur doloribus nobis repellat at quo est eum! Reiciendis ad quisquam assumenda sed asperiores, recusandae repudiandae, tempora, doloribus voluptatum molestias error perferendis aliquam delectus. Optio nesciunt, soluta fugit eligendi culpa cupiditate! Iusto repudiandae odit amet laborum rerum dolor autem quibusdam aut aliquam quisquam ab, eius natus magnam? Neque, aliquid excepturi quos commodi debitis voluptatem ullam magni, ex consectetur rerum ratione officiis quasi. Explicabo repellendus ea dolorem nihil distinctio iure, doloremque molestiae consequatur laudantium dolorum aperiam quo eos libero assumenda quod beatae sapiente, pariatur reiciendis eveniet vitae cumque deserunt officiis accusantium. Ab fugit enim, dolorum perspiciatis maxime vitae laboriosam optio temporibus rem pariatur tempore ut facilis nobis voluptatum. Libero natus est cum numquam rem eos dolorum nostrum, odit maiores quas ducimus voluptate molestiae commodi voluptatibus unde. Aliquam quisquam fugit deleniti unde vero illum quae aspernatur reiciendis ea alias ab voluptate, officiis natus cum suscipit nemo quo? Quibusdam minima porro accusantium iure facere perspiciatis nisi corporis molestias tempora eveniet? Fuga delectus quod ratione illum natus eos mollitia, eveniet veritatis, nostrum, sint eum quis accusamus inventore et repellat ducimus consequatur provident pariatur velit tempora similique. Ut, vero sit aliquid minus enim sunt amet saepe quam perspiciatis deserunt libero temporibus dignissimos ipsam sint, nesciunt vitae facilis, magnam autem assumenda voluptatem? Excepturi vitae recusandae molestias sunt dolorum explicabo, laudantium nemo debitis dignissimos placeat accusantium a.</p>
        </div>
    );
};

export default Sports;